### ISSUE TITLE
Keep sliding with NDI

### ISSUE THREAD

**Issue by ogmkp** [norihiro/obs-async-audio-filter#8]
Hi @norihiro 

Unfortunately, on Linux Debian with pipewire, the monitoring sound continues to shift with the NDI plugin.
Without obs-async-audio-filter plugin, the sound shifts more and more slowly.
With obs-async-audio-filter, the sound shifts more slowly and then suddenly, as if catching up with the late buffer as OBS wishes.

Tested with OBS time or source time.

In log I have many "removing one frame" and some "lock failed du to large error".

I tested with checked and unchecked the low buffering audio in the obs settings and obs restart.

Thanks.

**Comment by norihiro** [comment]
I didn't consider the monitoring sound with this plugin. Probably, PipeWire expects a different clock source than OBS.
So far, I don't think there is an API on OBS to do something on the monitoring audio and I have no idea to fix the issue on this plugin side.

> In log I have many "removing one frame" and some "lock failed due to large error".
The log `removing one frame` or `adding one frame` is normal. Sometimes it will appear every seconds or more.
Another log `lock failed due to large error` should not happen often. This will happen when the audio delays 70 ms or more. I guess the network quality is poor.

Could you provide what is the sender of your NDI?
How the network is connected between the sender and the receiver, wired or wireless?

If you just want to play the audio from NDI, I would suggest using FFmpeg. There is a patch to add NDI to FFmpeg.

**Comment by ogmkp** [comment]
Ok, I thought it was for monitoring, but I don't have any offset problem on the obs output at the encoder (for the moment).
The source is a Newtek Connect Spark to which I've plugged my game console.
There is no image or sound latency in the OBS internal output (encoder), just the monitoring from NDI to pipewire-pulse which shifts as it goes along (the problem doesn't exist for other sources such as mic In or media source).

The problem has been referenced https://github.com/obs-ndi/obs-ndi/issues/667  I was looking for a workaround.

**Comment by norihiro** [comment]
> I was looking for a workaround.

If you create a dummy audio device and monitor out to the dummy device, then loopback the dummy device to your actual device, it might fix the asynchronous issue.
  OBS audio monitor -> dummy device -> loopback -> actual device

Though I have not tried PipeWire yet, the loopback in PulseAudio does some trick so that above might change something.

**Comment by ogmkp** [comment]
I've already tried and tried again today with a virtual interface and it doesn't solve the problem with NDI, I'll wait for the obs-ndi project to find a solution.

Thanks for your help.
